//This file stores data regarding all the tehsils of districts in punjab
const amritsarTehsils = ['Amritsar-I', 'Amritsar-II', 'Ajnala',
'Baba Bakala', 'Majitha', 'Lopoke']
const barnalaTehsils = ['Barnala', 'Tapa', 'Mehal Kalan']
const bathindaTehsils = ['Bathinda', 'Rampura Phul', 'Talwandi sabo', 'Maur']
const faridkotTehsils = ['Faridkot', 'Kotkapura', 'Jaitu']
const fatehgarhSahibTehsils = ['Fatehgarh Sahib', 'Bassi Pathana', 'Amloh', 'Khamano', 'Mandi Gobindgarh', 'Chanarthal Kalan']
const fazilkaTehsils = ['Abohar', 'Fazilka', 'Jalalabad (West)']
const ferozepurTehsils = ['Ferozepur', 'Zira', 'Guru HarSahai']
const gurdaspurTehsils = ['Gurdaspur', 'Batala', 'Dera Baba Nanak', 'Dinanagar', 'kalanaur', 'Fategarh churian']
const hoshiarpurTehsils = ['Hoshiarpur', 'Dasuya', 'Mukerian', 'Garhshankar']
const jalandharTehsils = ['Jalandhar I', 'Jalandhar II', 'Nakodar', 'Phillaur', 'Shahkot']
const kapurthalaTehsils = ['Kapurthala', 'Sultanpur Lodhi', 'Phagwara', 'Bholath']
const ludhianaTehsils = ['Ludhiana East', 'Ludhiana West', 'Jagraon', 'Samrala', 'Khanna', 'Payal', 'Raikot']
const malerkotlaTehsils = []
const mogaTehsils = ['Moga', 'Baghapurana', 'Nihal Singh Wala', 'Dharmkot']
const mansaTehsils = ['Mansa', 'Sardulgarh', 'Budhlada']
const sriMuktsarSahibTehsils = ['Sri Muktsar Sahib', 'Gidderbaha', 'Malout']
const pathankotTehsils = ['Pathankot', 'DharKalan']
const patialaTehsils = ['Patiala', 'Nabha', 'Rajpura', 'Samana', 'Patran', 'Dhudhan Sadhan']
const rupNagarTehsils = ['Sri Anandpur Sahib', 'Sri Chamkaur Sahib', 'Rupnagar', 'Nangal', 'Morinda']
const sasNagarTehsils = ['Sahibzada Ajit Singh Nagar', 'Kharar', 'Dera Bassi']
const sbsNagarTehsils = ['Nawanshahr', 'Balachaur', 'Banga']
const tarnTaranTehsils = ['Khadoor Sahib', 'Patti', 'Bhikhiwind', 'Tarn Taran']
const sangrurTehsils = ['Sangrur', 'Dhuri', 'Sunam', 'Moonak', 'Lehra', 'Dirba', 'Bhawanigarh']

export {amritsarTehsils, barnalaTehsils, bathindaTehsils, faridkotTehsils, fatehgarhSahibTehsils, fazilkaTehsils, ferozepurTehsils, gurdaspurTehsils, hoshiarpurTehsils, jalandharTehsils, kapurthalaTehsils, ludhianaTehsils, malerkotlaTehsils, mogaTehsils, mansaTehsils,sriMuktsarSahibTehsils, pathankotTehsils, patialaTehsils, rupNagarTehsils, sasNagarTehsils,sbsNagarTehsils,sangrurTehsils,tarnTaranTehsils}